// ========================================================================================
// ROUTE CONSTANTS
// ========================================================================================

export const ROUTES = {
  USER: {
    HOME: "/",
    HOME_ALT: "/home",
    LOGIN: "/login",
    SIGNUP: "/signup",
    PAGE_NOT_FOUND: "/page-not-found",
    RESET_PASSWORD_CODE: "/reset-password/:code",
    RESET_PASSWORD: "/reset-password",
    NEW_PASSWORD: "/new-password",
    OTP_MESSAGE: "/otp-message",
    FORGOT_PASSWORD: "/forgot-password",
    OTP_VERIFICATION: "/otp-verification",
    AUTH_GOOGLE: "/auth/google",
    AUTH_GOOGLE_CALLBACK: "/auth/google/callback",
    RESEND_OTP: "/resend-otp",
    SHOP: "/shop",
    PRODUCT_DETAIL: "/product/:productId/:variantId",
    MY_ACCOUNT: "/my-account",
    ADD_ADDRESS: "/add-address",
    MANAGE_ADDRESS: "/manage-address",
    REMOVE_ADDRESS: "/remove-address/:addressId",
    EDIT_ADDRESS_ID: "/edit-address/:id",
    EDIT_ADDRESS_ACTION: "/edit-address/:addressId",
    BUY_NOW: "/buy-now",
    MY_CART: "/my-cart",
    ADD_TO_CART: "/add-to-cart",
    REMOVE_CART_PRODUCT: "/remove-cart-product",
    UPDATE_CART_PRODUCT: "/update-cart-product",
    CHECKOUT: "/checkout",
    PLACE_ORDER: "/place-order",
    VERIFY_COUPON: "/verify-coupon",
    PLACE_ORDER_BUY_NOW: "/placeOrderWithBuyNow",
    VERIFY_RAZORPAY: "/verify-razorpay-payment",
    MY_ORDERS: "/my-orders",
    CANCEL_ORDER: "/cancel-order",
    RETURN_ORDER: "/return-order",
    PAYMENT_FAILED_RETRY: "/payment-failed-retry",
    ORDER_DETAILS_DETAIL: "/product-details/:orderId/:productId/:variantId/:addressId",
    MY_WISHLIST: "/my-wishlist",
    ADD_TO_WISHLIST: "/add-to-wishlist/:id",
    MY_WALLET: "/my-wallet",
    ADD_MONEY_TO_WALLET: "/add-money-to-wallet",
    MY_COUPONS: "/my-coupons",
    SUBMIT_REVIEW: "/submit-review",
    EDIT_REVIEW: "/edit-review/:reviewId",
    SHARE_AND_EARN: "/share-and-earn",
    REDEEM_REFERRAL: "/redeem-referral",
    HELP: "/help",
    GET_APP: "/get-app",
    PRIVACY: "/privacy",
    TERMS: "/terms",
    LOGOUT: "/logout",
  },
  ADMIN: {
    LOGIN: "/admin-login",
    LOGOUT: "/admin-logout",
    DASHBOARD: "/dashboard",
    SALES_DATA: "/all-sales-data",
    TOP_ITEMS: "/top-items",
    PRODUCTS: "/products",
    PRODUCT_OFFER: "/product-offer",
    REMOVE_PRODUCT_OFFER: "/remove-product-offer/:productId",
    SEARCH_PRODUCTS: "/search-products",
    ADD_PRODUCTS: "/add-products",
    TOGGLE_PRODUCT: "/toggle-product/:id",
    TOGGLE_VARIANT: "/toggle-variant",
    TOP_PRODUCTS: "/top-products",
    EDIT_PRODUCT: "/edit-product/:productId/:variantId",
    ADD_VARIANTS: "/add-variants/:productId",
    ADD_NEW_VARIANTS: "/add-new-variants",
    BRANDS: "/brands",
    SEARCH_BRANDS: "/search-brands",
    TOGGLE_BRAND: "/toggle-brand/:id",
    ADD_NEW_BRAND: "/add-new-brand",
    EDIT_BRAND: "/edit-brand/:brandId",
    TOP_BRANDS: "/top-brands",
    CATEGORY: "/category",
    TOGGLE_CATEGORY: "/toggle-category/:id",
    TOGGLE_SUBCATEGORY: "/toggle-subcategory/:id",
    ADD_CATEGORY: "/add-category",
    ADD_SUBCATEGORY: "/add-subcategory",
    EDIT_CATEGORY: "/category/edit/:id",
    ADD_OFFER_ID: "/add-offer/:id",
    TOP_CATEGORIES: "/top-categories",
    TOP_SUBCATEGORIES: "/top-subcategories",
    ADD_OFFER: "/add-offer",
    REMOVE_OFFER: "/remove-offer/:categoryId",
    USERS: "/users",
    SEARCH_USER: "/search-user",
    BLOCK_USER: "/block-user",
    UNBLOCK_USER: "/unblock-user",
    COUPONS: "/coupons",
    ADD_COUPON: "/add-coupon",
    REMOVE_COUPON: "/remove-coupon",
    RESTORE_COUPON: "/restore-coupon",
    ORDERLISTS: "/orderlists",
    UPDATE_ORDER_STATUS: "/update-order-status",
    SETTINGS: "/settings",
    SETTINGS_UPDATE: "/settings/update",
  }
};

// View paths for rendering templates (relative paths without leading slash)
export const VIEWS = {
  USER: {
    HOME: "user/home",
    LOGIN: "user/login",
    SIGNUP: "user/signup",
    PAGE_404: "user/page-404",
    OTP_MESSAGE: "user/otp-message",
    OTP_VERIFICATION: "user/otp-verification",
    FORGOT_PASSWORD: "user/forgot-password",
    NEW_PASSWORD: "user/new-password",
    SHOP: "user/shop",
    PRODUCT_PAGE: "user/product-page",
    MY_ACCOUNT: "user/my-account",
    ADD_ADDRESS: "user/add-address",
    MANAGE_ADDRESS: "user/manage-address",
    EDIT_ADDRESS: "user/edit-address",
    MY_CART: "user/cart",
    CHECKOUT: "user/checkout",
    MY_ORDERS: "user/my-orders",
    ORDER_DETAILS: "user/order-details",
    MY_WISHLIST: "user/my-wishlist",
    MY_WALLET: "user/my-wallet",
    MY_COUPONS: "user/my-coupons",
    HELP: "user/help",
    GET_APP: "user/get-app",
    PRIVACY: "user/privacy",
    TERMS: "user/terms&conditions",
    SHARE_EARN: "user/shareAndEarn",
  },
  ADMIN: {
    LOGIN: "admin/admin-login",
    DASHBOARD: "admin/dashboard",
    PRODUCTS: "admin/products",
    ADD_PRODUCT: "admin/add-products",
    EDIT_PRODUCT: "admin/edit-product",
    ADD_VARIANT: "admin/add-variant",
    BRANDS: "admin/brands",
    ADD_BRAND: "admin/add-new-brand",
    EDIT_BRAND: "admin/edit-brand",
    CATEGORY: "admin/category",
    ADD_CATEGORY: "admin/add-category",
    EDIT_CATEGORY: "admin/edit-category",
    OFFER: "admin/offer",
    USERS: "admin/users",
    COUPONS: "admin/coupons",
    ORDER_LISTS: "admin/orderlists",
    SETTINGS: "admin/settings",
    TOP_ITEMS: "admin/top-items",
  }
};

// Absolute routes with prefix
export const ABSOLUTE = {
  USER: {
    HOME: "/home",
    LOGIN: "/login",
    SIGNUP: "/signup",
    PAGE_NOT_FOUND: "/page-not-found",
    RESET_PASSWORD_CODE: (code) => `/reset-password/${code}`,
    RESET_PASSWORD: "/reset-password",
    NEW_PASSWORD: "/new-password",
    OTP_MESSAGE: "/otp-message",
    FORGOT_PASSWORD: "/forgot-password",
    OTP_VERIFICATION: "/otp-verification",
    SHOP: "/shop",
    PRODUCT_DETAIL: (productId, variantId) => `/product/${productId}/${variantId}`,
    MY_ACCOUNT: "/my-account",
    ADD_ADDRESS: "/add-address",
    MANAGE_ADDRESS: "/manage-address",
    REMOVE_ADDRESS: (addressId) => `/remove-address/${addressId}`,
    EDIT_ADDRESS_ID: (id) => `/edit-address/${id}`,
    EDIT_ADDRESS_ACTION: (addressId) => `/edit-address/${addressId}`,
    BUY_NOW: "/buy-now",
    MY_CART: "/my-cart",
    ADD_TO_CART: "/add-to-cart",
    REMOVE_CART_PRODUCT: "/remove-cart-product",
    UPDATE_CART_PRODUCT: "/update-cart-product",
    CHECKOUT: "/checkout",
    PLACE_ORDER: "/place-order",
    VERIFY_COUPON: "/verify-coupon",
    PLACE_ORDER_BUY_NOW: "/placeOrderWithBuyNow",
    VERIFY_RAZORPAY: "/verify-razorpay-payment",
    MY_ORDERS: "/my-orders",
    CANCEL_ORDER: "/cancel-order",
    RETURN_ORDER: "/return-order",
    PAYMENT_FAILED_RETRY: "/payment-failed-retry",
    ORDER_DETAILS_DETAIL: (orderId, productId, variantId, addressId) => `/product-details/${orderId}/${productId}/${variantId}/${addressId}`,
    MY_WISHLIST: "/my-wishlist",
    ADD_TO_WISHLIST: (id) => `/add-to-wishlist/${id}`,
    MY_WALLET: "/my-wallet",
    ADD_MONEY_TO_WALLET: "/add-money-to-wallet",
    MY_COUPONS: "/my-coupons",
    SUBMIT_REVIEW: "/submit-review",
    EDIT_REVIEW: (reviewId) => `/edit-review/${reviewId}`,
    SHARE_AND_EARN: "/share-and-earn",
    REDEEM_REFERRAL: "/redeem-referral",
    HELP: "/help",
    GET_APP: "/get-app",
    PRIVACY: "/privacy",
    TERMS: "/terms",
    LOGOUT: "/logout",
  },
  ADMIN: {
    LOGIN: "/admin/admin-login",
    LOGOUT: "/admin/admin-logout",
    DASHBOARD: "/admin/dashboard",
    SALES_DATA: "/admin/all-sales-data",
    TOP_ITEMS: "/admin/top-items",
    PRODUCTS: "/admin/products",
    PRODUCT_OFFER: "/admin/product-offer",
    REMOVE_PRODUCT_OFFER: (productId) => `/admin/remove-product-offer/${productId}`,
    SEARCH_PRODUCTS: "/admin/search-products",
    ADD_PRODUCTS: "/admin/add-products",
    TOGGLE_PRODUCT: (id) => `/admin/toggle-product/${id}`,
    TOGGLE_VARIANT: "/admin/toggle-variant",
    TOP_PRODUCTS: "/admin/top-products",
    EDIT_PRODUCT: (productId, variantId) => `/admin/edit-product/${productId}/${variantId}`,
    ADD_VARIANTS: (productId) => `/admin/add-variants/${productId}`,
    ADD_NEW_VARIANTS: "/admin/add-new-variants",
    BRANDS: "/admin/brands",
    SEARCH_BRANDS: "/admin/search-brands",
    TOGGLE_BRAND: (id) => `/admin/toggle-brand/${id}`,
    ADD_NEW_BRAND: "/admin/add-new-brand",
    EDIT_BRAND: (brandId) => `/admin/edit-brand/${brandId}`,
    TOP_BRANDS: "/admin/top-brands",
    CATEGORY: "/admin/category",
    TOGGLE_CATEGORY: (id) => `/admin/toggle-category/${id}`,
    TOGGLE_SUBCATEGORY: (id) => `/admin/toggle-subcategory/${id}`,
    ADD_CATEGORY: "/admin/add-category",
    ADD_SUBCATEGORY: "/admin/add-subcategory",
    EDIT_CATEGORY: (id) => `/admin/category/edit/${id}`,
    ADD_OFFER_ID: (id) => `/admin/add-offer/${id}`,
    TOP_CATEGORIES: "/admin/top-categories",
    TOP_SUBCATEGORIES: "/admin/top-subcategories",
    ADD_OFFER: "/admin/add-offer",
    REMOVE_OFFER: (categoryId) => `/admin/remove-offer/${categoryId}`,
    USERS: "/admin/users",
    SEARCH_USER: "/admin/search-user",
    BLOCK_USER: "/admin/block-user",
    UNBLOCK_USER: "/admin/unblock-user",
    COUPONS: "/admin/coupons",
    ADD_COUPON: "/admin/add-coupon",
    REMOVE_COUPON: "/admin/remove-coupon",
    RESTORE_COUPON: "/admin/restore-coupon",
    ORDERLISTS: "/admin/orderlists",
    UPDATE_ORDER_STATUS: "/admin/update-order-status",
    SETTINGS: "/admin/settings",
    SETTINGS_UPDATE: "/admin/settings/update",
  }
};

export default { ROUTES, VIEWS, ABSOLUTE };